services:
  mysql-db:
    image: mysql:8.0
    container_name: my-sql
    environment:
      MYSQL_DATABASE: libraryDB
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  java-app:
    build: .
    container_name: library_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/libraryDB?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      mysql-db:
        condition: service_healthy
