CREATE TABLE autores(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    genero ENUM('MASCULINO', 'FEMININO', 'NAO_BINARIO', 'OUTRO', 'PREFIRO_NAO_DIZER'),
    data_Nascimento DATE NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL
);