CREATE TABLE locatarios(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    genero ENUM('MASCULINO', 'FEMININO', 'NAO_BINARIO', 'OUTRO', 'PREFIRO_NAO_DIZER'),
    telefone VARCHAR(16) NOT NULL ,
    email VARCHAR(100) NOT NULL UNIQUE ,
    data_Nascimento DATE NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL
);